### ISSUE TITLE
Migrating Snippets 

### ISSUE THREAD

**Issue by chraibi** [iv-mexx/gitlab-migrator#15]
Got the following error while migrating a project with snippets

```
/usr/local/lib/ruby/gems/2.3.0/gems/gitlab-3.7.0/lib/gitlab/request.rb:80:in `validate': [!] Server responded with code 400, 
message: 400 (Bad request) "file_name" not given. Request URI: https://gitlab.version.fz-juelich.de/api/v3/projects/251/snip$
ets (Gitlab::Error::BadRequest)
        from /usr/local/lib/ruby/gems/2.3.0/gems/gitlab-3.7.0/lib/gitlab/request.rb:49:in `post'
        from /usr/local/lib/ruby/gems/2.3.0/gems/gitlab-3.7.0/lib/gitlab/client/snippets.rb:44:in `create_snippet'
        from /Users/chraibi/Workspace/gitlab-migrator/fastlane/actions/gitlab_create_project.rb:121:in `block in migrate_sni$
pets'
        from /Users/chraibi/Workspace/gitlab-migrator/fastlane/actions/gitlab_create_project.rb:119:in `each'
        from /Users/chraibi/Workspace/gitlab-migrator/fastlane/actions/gitlab_create_project.rb:119:in `migrate_snippets'
        from /Users/chraibi/Workspace/gitlab-migrator/fastlane/actions/gitlab_create_project.rb:54:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:225:in `block (2 levels) ine$ecute_action'

```

the [API](https://docs.gitlab.com/ce/api/project_snippets.html) suggests the existence of the attribute `file_name`. 

According to the documentation when API-**creating** snippets `file_name`  is required, however 
snippets (created using the web-interface for instance) may have no `file_name`.

**Comment by iv-mexx** [comment]
Hm, the file name is set here: https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L113

But maybe, the original snippets `file_name` is empty for some reason in your case? 
Could you maybe verify this?

If so, we would just have to take a default `file_name`, maybe the name of the snippe?

**Comment by chraibi** [comment]
Yes, `snippet.file_name` is empty. I created a test project with some dummy snippets. 

Then inserted this  between [L110](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L110) and [L111](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L111)

```
if snippet.file_name.empty?                                                                                  
     snippet_file_name = snippet.title.delete(' ') + "." + snippet.id.to_s
else
     snippet_file_name = snippet.file_name
end                               
```
and use `snippet_file_name` in [L113](https://github.com/iv-mexx/gitlab-migrator/blob/master/fastlane/actions/gitlab_create_project.rb#L113)

These are some debugging messages (just for illustrating)

```
[11:01:47]: Migrating snippets
[11:01:51]: Snippet: 'test snippet without file '
[11:01:51]: Snippet: has no file_name
[11:01:51]: Snippet name is --> 'testsnippetwithoutfile.10'
[11:01:52]: Migrating snippet notes for snippet 10
[11:01:52]: Migrated snippet notes for snippet 10
[11:01:53]: Snippet: 'test internal snippet'
[11:01:53]: Snippet: filename is  hallo3.py
[11:01:53]: Snippet name is --> 'hallo3.py'
[11:01:54]: Migrating snippet notes for snippet 9
[11:01:54]: Migrated snippet notes for snippet 9
[11:01:55]: Snippet: 'Test private snuppet'
[11:01:55]: Snippet: filename is  hallo2.py
[11:01:55]: Snippet name is --> 'hallo2.py'
[11:01:56]: Migrating snippet notes for snippet 8
[11:01:56]: Migrated snippet notes for snippet 8
[11:01:58]: Snippet: 'Test  public Snippet'
[11:01:58]: Snippet: filename is  hallo.py
[11:01:58]: Snippet name is --> 'hallo.py'
[11:01:59]: Migrating snippet notes for snippet 7
[11:02:00]: Migrated snippet notes for snippet 7
```

**Comment by iv-mexx** [comment]
great, would you mind submitting a new PR for this?

**Comment by iv-mexx** [comment]
Thanks for the help on this!
